In [1]:
import pandas as pd
wine = pd.read_csv('https://bit.ly/wine_csv_data')

In [3]:
data = wine[['alcohol','sugar','pH']].to_numpy()
target = wine['class'].to_numpy()

In [4]:
from sklearn.model_selection import train_test_split
train_input, test_input, train_target, test_target = train_test_split(data, target, test_size=0.2, random_state = 42)

In [5]:
sub_input, val_input, sub_target, val_target = train_test_split(train_input, train_target, test_size = 0.2 , random_state = 42)

In [7]:
print(sub_input.shape, val_input.shape, test_input.shape)

(4157, 3) (1040, 3) (1300, 3)


In [9]:
from sklearn.tree import DecisionTreeClassifier
dt = DecisionTreeClassifier(random_state = 42)
dt.fit(sub_input, sub_target)
print(dt.score(sub_input, sub_target))
print(dt.score(val_input, val_target))

0.9971133028626413
0.864423076923077


In [11]:
from sklearn.model_selection import cross_validate
scores = cross_validate(dt, train_input, train_target)
print(scores)

{'fit_time': array([0.01724195, 0.00748539, 0.0084517 , 0.00841045, 0.00750852]), 'score_time': array([0.00103927, 0.00096059, 0.00203013, 0.00072241, 0.00109792]), 'test_score': array([0.86923077, 0.84615385, 0.87680462, 0.84889317, 0.83541867])}


In [13]:
import numpy as np
print(np.mean(scores['test_score']))

0.855300214703487


In [16]:
from sklearn.model_selection import StratifiedKFold
scores = cross_validate(dt, train_input, train_target, cv=StratifiedKFold())
print(np.mean(scores['test_score']))

0.855300214703487


In [20]:
splitter = StratifiedKFold(n_splits = 10, shuffle = True, random_state = 42)
scores = cross_validate(dt, train_input, train_target, cv=splitter)
print(np.mean(scores['test_score']))

0.8574181117533719


In [21]:
from sklearn.model_selection import GridSearchCV
params = {'min_impurity_decrease':[0.0001 , 0.0002, 0.0003, 0.0004, 0.0005]}
gs = GridSearchCV(DecisionTreeClassifier(random_state= 42),params,n_jobs = -1)

In [22]:
gs.fit(train_input,train_target)

GridSearchCV(estimator=DecisionTreeClassifier(random_state=42), n_jobs=-1,
             param_grid={'min_impurity_decrease': [0.0001, 0.0002, 0.0003,
                                                   0.0004, 0.0005]})

In [24]:
dt = gs.best_estimator_
print(dt.score(train_input, train_target))

0.9615162593804117


In [25]:
print(gs.best_params_)

{'min_impurity_decrease': 0.0001}


In [26]:
print(gs.cv_results_['mean_test_score'])

[0.86819297 0.86453617 0.86492226 0.86780891 0.86761605]


In [28]:
best_index = np.argmax(gs.cv_results_['mean_test_score'])
print(gs.cv_results_['params'][best_index])

{'min_impurity_decrease': 0.0001}


In [31]:
params = {'min_impurity_decrease': np.arange(0.0001, 0.001, 0.0001),
          'max_depth':range(5, 20, 1),
          'min_samples_split':range(2,100,10)
          }

gs= GridSearchCV(DecisionTreeClassifier(random_state = 42 ),params, n_jobs=-1)
gs.fit(train_input, train_target)

GridSearchCV(estimator=DecisionTreeClassifier(random_state=42), n_jobs=-1,
             param_grid={'max_depth': range(5, 20),
                         'min_impurity_decrease': array([0.0001, 0.0002, 0.0003, 0.0004, 0.0005, 0.0006, 0.0007, 0.0008,
       0.0009]),
                         'min_samples_split': range(2, 100, 10)})

In [32]:
print(gs.best_params_)

{'max_depth': 14, 'min_impurity_decrease': 0.0004, 'min_samples_split': 12}


In [33]:
print(np.max(gs.cv_results_['mean_test_score']))

0.8683865773302731


In [35]:
from scipy.stats import uniform, randint
rgen = randint(0, 10)
rgen.rvs(10)

array([0, 6, 2, 4, 4, 2, 2, 7, 5, 3])

In [37]:
np.unique(rgen.rvs(1000), return_counts=True)

(array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),
 array([109,  87,  79, 107, 116, 103,  94,  99, 105, 101]))

In [38]:
ugen = uniform(0,1)
ugen.rvs(10)

array([0.16298617, 0.35646739, 0.1245113 , 0.83259347, 0.40441812,
       0.74359883, 0.56428296, 0.81723188, 0.63051007, 0.75573924])

In [51]:
params ={'min_impurity_decrease': uniform(0.0001, 0.001),
         'max_depth':randint(20,50),
         'min_samples_split': randint(2,25),
         'min_samples_leaf': randint(1,25),
         }

from sklearn.model_selection import RandomizedSearchCV
gs = RandomizedSearchCV(DecisionTreeClassifier(random_state = 42), params,
                        n_iter=10000, n_jobs=-1, random_state = 42)
gs.fit(train_input, train_target)

RandomizedSearchCV(estimator=DecisionTreeClassifier(random_state=42),
                   n_iter=10000, n_jobs=-1,
                   param_distributions={'max_depth': <scipy.stats._distn_infrastructure.rv_frozen object at 0x7f31c0344bb0>,
                                        'min_impurity_decrease': <scipy.stats._distn_infrastructure.rv_frozen object at 0x7f31c0344730>,
                                        'min_samples_leaf': <scipy.stats._distn_infrastructure.rv_frozen object at 0x7f31c1adab80>,
                                        'min_samples_split': <scipy.stats._distn_infrastructure.rv_frozen object at 0x7f31c04d9c40>},
                   random_state=42)

In [52]:
print(gs.best_params_)

{'max_depth': 21, 'min_impurity_decrease': 0.00042479287078831576, 'min_samples_leaf': 4, 'min_samples_split': 14}


In [53]:
print(np.max(gs.cv_results_['mean_test_score']))

0.8705028873917229


In [54]:
dt = gs.best_estimator_
print(dt.score(test_input, test_target))

0.8607692307692307
